/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author secacad-sistemas
 */
public class FrmCitas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Forma2
     */
    public FrmCitas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtdetalleperro = new javax.swing.JTextField();
        jcbxveterinario = new javax.swing.JComboBox<>();
        jtxtPrecio = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        jdchFechaProgramada = new com.toedter.calendar.JDateChooser();
        jcbxdnicli = new javax.swing.JComboBox<>();
        jdchFechaReservacion = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtdetalleperro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DETALLES DEL PERRO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        getContentPane().add(jtxtdetalleperro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 440, 80));

        jcbxveterinario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VETERINARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        getContentPane().add(jcbxveterinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 220, 80));

        jtxtPrecio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRECIO DE RESERVA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        getContentPane().add(jtxtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 440, 80));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrar.setBackground(new java.awt.Color(102, 102, 255));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 180, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 410, 130));

        jdchFechaProgramada.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FECHA PROGRAMADA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        getContentPane().add(jdchFechaProgramada, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 220, 80));

        jcbxdnicli.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DNI CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        getContentPane().add(jcbxdnicli, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 210, 80));

        jdchFechaReservacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FECHA DE RESERVACION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        getContentPane().add(jdchFechaReservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 220, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRegistrar;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JComboBox<String> jcbxdnicli;
    public javax.swing.JComboBox<String> jcbxveterinario;
    public com.toedter.calendar.JDateChooser jdchFechaProgramada;
    public com.toedter.calendar.JDateChooser jdchFechaReservacion;
    public javax.swing.JTextField jtxtPrecio;
    public javax.swing.JTextField jtxtdetalleperro;
    // End of variables declaration//GEN-END:variables
}
