/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author secacad-sistemas
 */
public class FrmProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Forma2
     */
    public FrmProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtNombreProducto = new javax.swing.JTextField();
        jcbxCategoria = new javax.swing.JComboBox<>();
        jtxtCantidadProducto = new javax.swing.JTextField();
        jtxtPrecio = new javax.swing.JTextField();
        jspnStock = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        jdchFechaVencimiento = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtNombreProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NOMBRE DE PRODUCTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        getContentPane().add(jtxtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 80));

        jcbxCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CATEGORIA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        getContentPane().add(jcbxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 430, 80));

        jtxtCantidadProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CANTIDAD POR PRODUCTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        getContentPane().add(jtxtCantidadProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 240, 80));

        jtxtPrecio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRECIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        getContentPane().add(jtxtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 190, 80));

        jspnStock.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STOCK", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        getContentPane().add(jspnStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 210, 70));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrar.setBackground(new java.awt.Color(102, 102, 255));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 180, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 410, 130));

        jdchFechaVencimiento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FECHA DE VENCIMIENTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        getContentPane().add(jdchFechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 220, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRegistrar;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JComboBox<String> jcbxCategoria;
    public com.toedter.calendar.JDateChooser jdchFechaVencimiento;
    public javax.swing.JSpinner jspnStock;
    public javax.swing.JTextField jtxtCantidadProducto;
    public javax.swing.JTextField jtxtNombreProducto;
    public javax.swing.JTextField jtxtPrecio;
    // End of variables declaration//GEN-END:variables
}
