/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author secacad-sistemas
 */
public class FormularioMenu extends javax.swing.JFrame {

    /**
     * Creates new form FormularioMenu
     */
    public FormularioMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpnContenedor = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mitemRegistroCliente = new javax.swing.JMenuItem();
        mitemRegistroCita = new javax.swing.JMenuItem();
        mitemlistacita = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemcatprod = new javax.swing.JMenuItem();
        itemprod = new javax.swing.JMenuItem();
        itemprodstock = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jdpnContenedor.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jdpnContenedorLayout = new javax.swing.GroupLayout(jdpnContenedor);
        jdpnContenedor.setLayout(jdpnContenedorLayout);
        jdpnContenedorLayout.setHorizontalGroup(
            jdpnContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1540, Short.MAX_VALUE)
        );
        jdpnContenedorLayout.setVerticalGroup(
            jdpnContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );

        getContentPane().add(jdpnContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 840));

        jMenu1.setText("Registro Citas");

        mitemRegistroCliente.setText("Registrar Clientes");
        mitemRegistroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemRegistroClienteActionPerformed(evt);
            }
        });
        jMenu1.add(mitemRegistroCliente);

        mitemRegistroCita.setText("Registrar Citas");
        jMenu1.add(mitemRegistroCita);

        mitemlistacita.setText("Lista de Citas");
        mitemlistacita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemlistacitaActionPerformed(evt);
            }
        });
        jMenu1.add(mitemlistacita);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Productos");

        itemcatprod.setText("Registrar Categorias");
        itemcatprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemcatprodActionPerformed(evt);
            }
        });
        jMenu2.add(itemcatprod);

        itemprod.setText("Registrar Productos");
        itemprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemprodActionPerformed(evt);
            }
        });
        jMenu2.add(itemprod);

        itemprodstock.setText("Productos en Stock");
        jMenu2.add(itemprodstock);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitemRegistroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemRegistroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mitemRegistroClienteActionPerformed

    private void itemprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemprodActionPerformed

    private void itemcatprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemcatprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemcatprodActionPerformed

    private void mitemlistacitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemlistacitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mitemlistacitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem itemcatprod;
    public javax.swing.JMenuItem itemprod;
    public javax.swing.JMenuItem itemprodstock;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JDesktopPane jdpnContenedor;
    public javax.swing.JMenuItem mitemRegistroCita;
    public javax.swing.JMenuItem mitemRegistroCliente;
    public javax.swing.JMenuItem mitemlistacita;
    // End of variables declaration//GEN-END:variables
}
